import requests
import pytest

# Integration tests generated by ChatGPT

def test_valid_user(mocker):
    url = "http://127.0.0.1:8000/users/?username=admin&password=qwerty"
    mock_response = mocker.Mock()
    mock_response.status_code = 200
    mock_response.text = ''
    mocker.patch('requests.get', return_value=mock_response)

    response = requests.get(url)

    assert response.status_code == 200
    assert response.text.strip() == ''

def test_invalid_user(mocker):
    url = "http://127.0.0.1:8000/users/?username=admin&password=admin"
    mock_response = mocker.Mock()
    mock_response.status_code = 401
    mock_response.text = ''
    mocker.patch('requests.get', return_value=mock_response)

    response = requests.get(url)

    assert response.status_code == 401
    assert response.text.strip() == ''